[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
app.workspace = true
axum = "0.6.1"
dioxus = { workspace = true, features = ["ssr"] }
tokio = { version = "1.23.0", features = ["full"] }
tower-http = { version = "0.3.5", features = ["fs"] }
